var BeeEffects = {
    EFFECT_NONE: 0,
    EFFECT_AGGRESS: 1,
    EFFECT_BEATIFIC: 2,
    EFFECT_CREEPER: 3,
    EFFECT_EXPLORER: 4,
    EFFECT_FREEZING: 5,
    EFFECT_HEROIC: 6,
    EFFECT_FLAMMABLE: 7,
    EFFECT_POISON: 8,
    EFFECT_ENDS: 9,
    EFFECT_RADIOACT: 10,
    EFFECT_DRUNKARD: 11,
    EFFECT_REPULSION: 12,
    EFFECT_REANIMATION: 13
};